function togglePlayers() {
  var playerListSection = document.getElementById("player-list");
  playerListSection.innerHTML = "index player.html"; // Clear existing content

  // Define player information for each team
  var players = {
    "Liverpool"[{image:"liverpool.png"}]: ["1. Alisson-Goalkeeper", "2. Joe Gomez-Defender","3. Wataru Endo-Midfielder", "4. Virgil van Dijk-Defender","5. Ibrahima Konate-Defender","6. Thiago-Midfielder","7. Luis Diaz-Forward","8. Dominik Szoboszlai-Midfielder","9. Darwin Nunez-Forward","10. Alexis Mac Allister-Midfielder","11. Mohamed Salah-Forward","13. Adrian-Goalkeeper","17. Curtis Jones-Midfielder","18. Cody Gakpo-Forward","19. Harvey Elliott-Midfielder","20. Diogo Jota-Forward","21. Kostas Tsimikas-Defender","26. Andy Robertson-Defender","32. Joel Matip-Defender","38. Ryan Gravenberch-Midfielder","42. Bobby Clark-Midfielder","43. Stefan Bajcetic-Midfielder","50. Ben Doak-Forward","53. James McConnell-Midfielder","62. Caoimhin Kelleher-Goalkeeper","66. Trent Alexander-Arnold-Defender","78. Jarell Quansah-Defender","84. Conor Bradley-Defender",],
    "Manchester City": ["2.Kyle Walker-Defender","3.Ruben Dias-Defender","4.Kalvin Phillips-Defender","5.John Stones-Defender","6.Nathan Ake-Defender","7.Joao Cancelo-Defender","8.Mateo Kovacic-Midfielder","9.Erling Haaland-Forword","10.Jack Grealish-Midfielder","13.Zack Steffen-GoalKeeper","14.Aymeric Laporte-Defender","16.Rodri-Midfielder","16.Rodri-Midfielder","18.Stefan Moreno-Goalkeeper","19.Julian Alvarez-Forward","20.Bernardo Silva-Defender","21.Sergio Gomez-Defender","25.Manuel Akanji-Defender","31.Ederson-Goalkeeper","32.Maximo Perrone-Midfielder","33.Scott Carson-Goalkeeper","47.Phil Foden-	Forward","82.Rico Lewis-Defender","97.Joshua Wilson Esbrand-Defender",],
    "Manchester United": ["David de Gea - Goalkeeper - Jersey No: 1","Aaron Wan-Bissaka - Defender - Jersey No: 29","Eric Bailly - Defender - Jersey No: 3","Phil Jones - Defender - Jersey No: 4","Harry Maguire - Defender - Jersey No: 5","Luke Shaw - Defender - Jersey No: 23","Victor Lindelöf - Defender - Jersey No: 2","Diogo Dalot - Defender - Jersey No: 20","Alex Telles - Defender - Jersey No: 27","Bruno Fernandes - Midfielder - Jersey No: 18","Fred - Midfielder - Jersey No: 17","Nemanja Matić - Midfielder - Jersey No: 31","Paul Pogba - Midfielder - Jersey No: 6","Jesse Lingard - Midfielder - Jersey No: 14","Donny van de Beek - Midfielder - Jersey No: 34","Scott McTominay - Midfielder - Jersey No: 39","Marcus Rashford - Forward - Jersey No: 10","Anthony Martial - Forward - Jersey No: 9","Edinson Cavani - Forward - Jersey No: 7","Mason Greenwood - Forward - Jersey No: 11","Amad Diallo - Forward - Jersey No: 19","Shola Shoretire - Forward - Jersey No: 74","Dean Henderson - Goalkeeper - Jersey No: 26","Lee Grant - Goalkeeper - Jersey No: 13","Anthony Elanga - Forward - Jersey No: 56","Ethan Galbraith - Midfielder - Jersey No: 38","Hannibal Mejbri - Midfielder - Jersey No: 43","Teden Mengi - Defender - Jersey No: 56","Will Fish - Defender - Jersey No: 55","Charlie McNeill - Forward - Jersey No: 54",],
    "Brighton": ["Robert Sánchez - Goalkeeper - Jersey No: 26","Jason Steele - Goalkeeper - Jersey No: 23","Lewis Dunk - Defender - Jersey No: 5","Adam Webster - Defender - Jersey No: 4","Dan Burn - Defender - Jersey No: 33","Joël Veltman - Defender - Jersey No: 34","Shane Duffy - Defender - Jersey No: 6","Solly March - Midfielder - Jersey No: 20","Yves Bissouma - Midfielder - Jersey No: 8","Pascal Groß - Midfielder - Jersey No: 13","Leandro Trossard - Midfielder - Jersey No: 11","Davy Pröpper - Midfielder - Jersey No: 24","Dale Stephens - Midfielder - Jersey No: 6","Jakub Moder - Midfielder - Jersey No: 17","Steven Alzate - Midfielder - Jersey No: 46","Alexis Mac Allister - Midfielder - Jersey No: 10","Taylor Richards - Midfielder - Jersey No: 47","Alireza Jahanbakhsh - Forward - Jersey No: 16","Neal Maupay - Forward - Jersey No: 9","Danny Welbeck - Forward - Jersey No: 18","Andi Zeqiri - Forward - Jersey No: 14","Aaron Connolly - Forward - Jersey No: 44","Tariq Lamptey - Defender - Jersey No: 2","Adam Lallana - Midfielder - Jersey No: 14","Enock Mwepu - Midfielder - Jersey No: 46","Marc Cucurella - Defender - Jersey No: 15",],
    "Wolves": ["1.Jose Sa-Goalkeeper","25.Dan Bentley","40.Tom King-Goalkeeper","2.Matt Doherty","3.Rayan Ait Nouri-Defender","4.Satiago Bueno-Defender","15.Craig Dawson-Defender","17.Hugo Bueno-Defender","22.Nelson Semedo-Defender","23.Maximilian Kilman-Defender","24.Toti-Defender","5.Mario Lemina-Midfielder","6.Boubacar Traore-Midfielder","8.Joao Gomez-Midfielder","20.Tommy Doyle-Midfielder","27.Jean Ricner Bellagarde-Midfielder","7.Pedro Neto-Forward","11.Hee Chan Hwang-Forward","12.Matheus Cunha-Forward","14.Noah Lemina","21.Paulo Sarabia-Forward","30.Enso Gonzalez-Forward","63.Natan Fraser-Forward"],
    "Newcaslte":["1.Martin Dubravka-GoalKeeper","18.Loris Karius-GoalKeeper","21.Tino Livramento-Goalkeeper","33.Dan Burn-Goalkeeper","7.Joelinton-Midfielder","8.Sandro Tonali-Midfielder","11.Matt Ritchie-Midfielder","23.Jacob Murphy-Midfielder","32.Elliot Anderson-Midfielder","36.Sean Longstaff-Midfielder","39.Bruno Guimaraes-Midfielder","67.Lewis Miley-Midfielder","9.Callum Wilson-Forwords","10.Anthony Gordon-Forwords","14.Alexander Isak-Forwords","15.Harvey Barnes-Forwords",],
    "Brentford": ["David Raya - Goalkeeper - Jersey No: 1","Pontus Jansson - Defender - Jersey No: 5","Mads Bech Sørensen - Defender - Jersey No: 6",
    "Vitaly Janelt - Midfielder - Jersey No: 8","Mathias Jensen - Midfielder - Jersey No: 10","Sergi Canós - Forward - Jersey No: 7",
    "Ivan Toney - Forward - Jersey No: 17","Winston Reid - Defender - Jersey No: 18","Christian Nørgaard - Midfielder - Jersey No: 6","Emiliano Marcondes - Midfielder - Jersey No: 20","Bryan Mbeumo - Forward - Jersey No: 19","Mads Roerslev Rasmussen - Defender - Jersey No: 22","Marcus Forss - Forward - Jersey No: 24","Rico Henry - Defender - Jersey No: 3","Frank Onyeka - Midfielder - Jersey No: 28","Shandon Baptiste - Midfielder - Jersey No: 29","Luke Daniels - Goalkeeper - Jersey No: 28","Charlie Goode - Defender - Jersey No: 30","Dom Thompson - Defender - Jersey No: 29","Alvaro Fernandez - Goalkeeper - Jersey No: 33","Yoane Wissa - Forward - Jersey No: 9","Myles Peart-Harris - Midfielder - Jersey No: 31","Fin Stevens - Defender - Jersey No: 32",],
    "Chelsea": ["Kepa Arrizabalaga (Goalkeeper) - Jersey No. 1","Édouard Mendy (Goalkeeper) - Jersey No. 16","Marcus Bettinelli (Goalkeeper) - Jersey No. 13","Antonio Rüdiger (Defender) - Jersey No. 2","Thiago Silva (Defender) - Jersey No. 6","Andreas Christensen (Defender) - Jersey No. 4","Trevoh Chalobah (Defender) - Jersey No. 14","Reece James (Defender) - Jersey No. 24","Ben Chilwell (Defender) - Jersey No. 21","César Azpilicueta (Defender) - Jersey No. 28","Emerson Palmieri (Defender) - Jersey No. 33","Malang Sarr (Defender) - Jersey No. 3","Jorginho (Midfielder) - Jersey No. 5","Mateo Kovačić (Midfielder) - Jersey No. 17","N'Golo Kanté (Midfielder) - Jersey No. 7","Ruben Loftus-Cheek (Midfielder) - Jersey No. 12","Ross Barkley (Midfielder) - Jersey No. 8","Mason Mount (Midfielder) - Jersey No. 19","Hakim Ziyech (Midfielder) - Jersey No. 22","Christian Pulisic (Forward) - Jersey No. 10","Callum Hudson-Odoi (Forward) - Jersey No. 20","Timo Werner (Forward) - Jersey No. 11","Romelu Lukaku (Forward) - Jersey No. 9","Kai Havertz (Forward) - Jersey No. 29","Charly Musonda Jr. (Forward) - Jersey No. 1",],
    "Arsenal": ["1.Bernd Leno-Goalkeepeer", "Emiliano Martínez (No. 26)-Goalkeeper"," Mat Ryan(No. 33)–Goalkeeper", "Hector Bellerin (No. 2) - Right-back","Kieran Tierney (No. 3) - Leftback","GabrielMagalhães (No. 6) - Centre-back","Ben White (No. 4) - Centre-back","Rob Holding (No. 16) - Centreback", "Calum Chambers (No. 21) – Defender","Cedric Soares (No. 17) – Defender","Pablo Marí (No.22) - Centre-back","Thomas Partey (No. 5) - Defensive midfielder","Emile Smith Rowe (No. 10) -Attacking midfielder","Martin Ødegaard (No. 8) - Attacking midfielder","Albert Sambi Lokonga (No.23) - Central midfielder","Granit Xhaka (No. 34) - Central midfielder","insley Maitland-Niles (No. 15)– Midfielder","Bukayo Saka (No. 7) – Winger","Nicolas Pépé (No. 19) – Winger","Reiss Nelson (No.24) – Midfielder","Pierre Emerick Aubameyang (No. 14) – Striker","Alexandre Lacazette (No. 9) –Striker","Eddie Nketiah (No. 30) – Striker",],
    "Aston Villa": ["1.Emiliano Martínez-Goalkeeper","18.Joe Gauchi-Goalkeeper","25.Robin Olsen-Goalkeeper","2.Matty Cash-Defender","Ezri Konsa (Number 4) - Center-back","Tyrone Mings (Number 5) - Center-back","Matt Targett (Number 18) - Left-back","John McGinn (Number 7)","Douglas Luiz (Number 6)","Morgan Sanson (Number 8)","Jacob Ramsey (Number 41)","Marvelous Nakamba (Number 19)","Ollie Watkins (Number 11) - Forward","Danny Ings (Number 20) - Forward","Leon Bailey (Number 21) - Winger/Forward",],
    "Fulham": ["Goalkeepers:","Marek Rodák (Number 12)","Fabri (Number 31)","Harry Lewis (Number 63)","Defenders:","Tosin Adarabioyo (Number 16)","Tim Ream (Number 13)","Joe Bryan (Number 23)","Antonee Robinson (Number 3)","Denis Odoi (Number 4)","Michael Hector (Number 3)","Midfielders:","Harrison Reed (Number 21)","André-Frank Zambo Anguissa (Number 29)","Tom Cairney (Number 10)","Neeskens Kebano (Number 7)","Josh Onomah (Number 25)","Mario Lemina (Number 18)","Forwards:","Aleksandar Mitrović (Number 9)","Bobby Decordova-Reid (Number 14)","Ivan Cavaleiro (Number 17)","Ademola Lookman (Number 19)","Anthony Knockaert (Number 24)",],
    "Everton":["Jordan Pickford - Goalkeeper - Jersey No: 1","Jonjoe Kenny - Defender - Jersey No: 43","Michael Keane - Defender - Jersey No: 5","Lucas Digne - Defender - Jersey No: 12","Yerry Mina - Defender - Jersey No: 13","Ben Godfrey - Defender - Jersey No: 22","Andros Townsend - Forward - Jersey No: 15","Abdoulaye Doucouré - Midfielder - Jersey No: 16","Fabian Delph - Midfielder - Jersey No: 8","Allan - Midfielder - Jersey No: 6","Richarlison - Forward - Jersey No: 7","Dominic Calvert-Lewin - Forward - Jersey No: 9","Salomón Rondón - Forward - Jersey No: 23","Alex Iwobi - Midfielder - Jersey No: 17","Anthony Gordon - Forward - Jersey No: 42","Tom Davies - Midfielder - Jersey No: 26","Mason Holgate - Defender - Jersey No: 4","Nathan Broadhead - Forward - Jersey No: 31","Jean-Philippe Gbamin - Midfielder - Jersey No: 25","Asmir Begović - Goalkeeper - Jersey No: 33","Niels Nkounkou - Defender - Jersey No: 27","Jonas Lössl - Goalkeeper - Jersey No: 49","Jarrad Branthwaite - Defender - Jersey No: 54","Harry Tyrer - Goalkeeper - Jersey No: 51","Ellis Simms - Forward - Jersey No: 55",],
    "Luton Town": ["Simon Sluga - Goalkeeper - Jersey No: 12","James Shea - Goalkeeper - Jersey No: 36","Matty Pearson - Defender - Jersey No: 5","Tom Lockyer - Defender - Jersey No: 6","Sonny Bradley - Defender - Jersey No: 4","Reece Burke - Defender - Jersey No: 26","Gabriel Osho - Defender - Jersey No: 2","Dan Potts - Defender - Jersey No: 3","Kiernan Dewsbury-Hall - Midfielder - Jersey No: 8","Pelly-Ruddock Mpanzu - Midfielder - Jersey No: 17","Jordan Clark - Midfielder - Jersey No: 7","Harry Cornick - Forward - Jersey No: 14","George Moncur - Midfielder - Jersey No: 10","Elijah Adebayo - Forward - Jersey No: 19","Cameron Jerome - Forward - Jersey No: 9","Danny Hylton - Forward - Jersey No: 20","Henri Lansbury - Midfielder - Jersey No: 22","Elliot Lee - Forward - Jersey No: 11","Glen Rea - Midfielder - Jersey No: 24","Luke Berry - Midfielder - Jersey No: 18","Jordan Clark - Midfielder - Jersey No: 7","Sam Beckwith - Defender - Jersey No: 15","James Bree - Defender - Jersey No: 23","Kyran Lofthouse - Defender - Jersey No: 28","Jack Stacey - Defender - Jersey No: 16","Josh Neufville - Midfielder - Jersey No: 21","George Moncur - Midfielder - Jersey No: 27",],
    "Burnley": ["15.Bailey Peacock-Farrell - Goalkeeper","2.Matt Lowton - Defender","3.Charlie Taylor - Defender","4.Jack Cork - Midfielder","5.James Tarkowski - Defender","6.Ben Mee - Defender","7.Johann Berg Gudmundsson - Midfielder","Josh Brownhill - Midfielder","Chris Wood - Forward","Ashley Barnes - Forward","Dwight McNeil - Midfielder","Robbie Brady - Midfielder","Jeff Hendrick - Midfielder","Ben Gibson - Defender","Bailey Peacock Farrell - Goalkeeper","Dale Stephens - Midfielder","Matej Vydra - Forward","Ashley Westwood - Midfielder","Jimmy Dunne - Defender","Jay Rodriguez - Forward","Erik Pieters - Defender/Midfielder","Josh Benson - Midfielder",],
    "A.F.C. Bournemouth": ["Mark Travers - Goalkeeper - Jersey No: 27","Asmir Begović - Goalkeeper - Jersey No: 1","Gary Cahill - Defender - Jersey No: 14","Chris Mepham - Defender - Jersey No: 6","Steve Cook - Defender - Jersey No: 3","Jordan Zemura - Defender - Jersey No: 15","Lloyd Kelly - Defender - Jersey No: 5","Cameron Carter-Vickers - Defender - Jersey No: 32","Jordan Zemura - Defender - Jersey No: 33","Leif Davis - Defender - Jersey No: 23","Taylor Harwood-Bellis - Defender - Jersey No: 25","Junior Stanislas - Midfielder - Jersey No: 19","Jefferson Lerma - Midfielder - Jersey No: 8","Philip Billing - Midfielder - Jersey No: 29","Lewis Cook - Midfielder - Jersey No: 16","Dan Gosling - Midfielder - Jersey No: 4","Ben Pearson - Midfielder - Jersey No: 21","Jack Wilshere - Midfielder - Jersey No: 32","Emerson Hyndman - Midfielder - Jersey No: 4","David Brooks - Midfielder - Jersey No: 7","Arnaut Danjuma - Forward - Jersey No: 10","Sam Surridge - Forward - Jersey No: 20","Shane Long - Forward - Jersey No: 9","Jaidon Anthony - Forward - Jersey No: 14","Rico Richards - Forward - Jersey No: 28",],
    "Crystal Palace": ["Vicente Guaita - Goalkeeper - Jersey No: 31","Joachim Andersen - Defender - Jersey No: 3","Marc Guéhi - Defender - Jersey No: 6","Tyrick Mitchell - Defender - Jersey No: 21","Cheikhou Kouyaté - Midfielder - Jersey No: 8","Connor Gallagher - Midfielder - Jersey No: 23",
    "Jairo Riedewald - Midfielder - Jersey No: 44","Jordan Ayew - Forward - Jersey No: 9","Jeffrey Schlupp - Midfielder - Jersey No: 15","Wilfried Zaha - Forward - Jersey No: 11","Michael Olise - Midfielder - Jersey No: 7","Christian Benteke - Forward - Jersey No: 20","Jean-Philippe Mateta - Forward - Jersey No: 14","James Tomkins - Defender - Jersey No: 5","James McArthur - Midfielder - Jersey No: 18","Luka Milivojević - Midfielder - Jersey No: 4","Jordan Ayew - Forward - Jersey No: 20","Andros Townsend - Forward - Jersey No: 10","Nathaniel Clyne - Defender - Jersey No: 2","James McCarthy - Midfielder - Jersey No: 22","Jarosław Jach - Defender - Jersey No: 34","Martin Kelly - Defender - Jersey No: 34","Jack Butland - Goalkeeper - Jersey No: 13","Levi Lumeka - Forward - Jersey No: 36","Zachary Awe - Defender - Jersey No: 44","Jay Rich-Baghuelou - Defender -Jersey No: 45","Brandon Pierrick - Forward - Jersey No: 46",],
    "Sheffield United": ["Aaron Ramsdale - Goalkeeper - Jersey No: 1","Wes Foderingham - Goalkeeper - Jersey No: 18","Jayden Bogle - Defender - Jersey No: 20","Ethan Ampadu - Defender - Jersey No: 22","John Egan - Defender - Jersey No: 12","Chris Basham - Defender - Jersey No: 6","George Baldock - Defender - Jersey No: 2","Enda Stevens - Defender - Jersey No: 3","Jack Robinson - Defender - Jersey No: 14","Oliver Norwood - Midfielder - Jersey No: 16","John Fleck - Midfielder - Jersey No: 4","John Lundstram - Midfielder - Jersey No: 7","Sander Berge - Midfielder - Jersey No: 32","Ben Osborn - Midfielder - Jersey No: 23","Lys Mousset - Forward - Jersey No: 17","Rhian Brewster - Forward - Jersey No: 24","Oliver Burke - Forward - Jersey No: 11","Billy Sharp - Forward - Jersey No: 10","David McGoldrick - Forward - Jersey No: 17","Rhys Norrington-Davies - Defender - Jersey No: 21","Kyron Gordon - Defender - Jersey No: 34","Iliman Ndiaye - Midfielder - Jersey No: 42","Zak Brunt - Midfielder - Jersey No: 43","Regan Slater - Midfielder - Jersey No: 27","Daniel Jebbison - Forward - Jersey No: 29",],
    "Tottenham Hotspur": ["Hugo Lloris - Goalkeeper - Jersey No: 1","Matt Doherty - Defender - Jersey No: 2","Sergio Reguilón - Defender - Jersey No: 3","Toby Alderweireld - Defender - Jersey No: 4","Pierre-Emile Højbjerg - Midfielder - Jersey No: 5","Davinson Sánchez - Defender - Jersey No: 6","Heung-Min Son - Forward - Jersey No: 7","Harry Winks - Midfielder - Jersey No: 8","Harry Kane - Forward - Jersey No: 9","Giovani Lo Celso - Midfielder - Jersey No: 10","Steven Bergwijn - Forward - Jersey No: 11","Joe Hart - Goalkeeper - Jersey No: 12","Joe Rodon - Defender - Jersey No: 13","Eric Dier - Defender - Jersey No: 15","Eric Lamela - Forward - Jersey No: 11",
     "Gareth Bale - Forward - Jersey No: 9","Moussa Sissoko - Midfielder - Jersey No: 17","Giovanni Lo Celso - Midfielder - Jersey No: 18","Ryan Sessegnon - Midfielder - Jersey No: 19","Dele Alli - Midfielder - Jersey No: 20","Juan Foyth - Defender - Jersey No: 21","Pierre-Emile Højbjerg - Midfielder - Jersey No: 23","Tanguy Ndombele - Midfielder - Jersey No: 28","Harry Kane - Forward - Jersey No: 29","Oliver Skipp - Midfielder - Jersey No: 29","Ben Davies - Defender - Jersey No: 33","Cameron Carter-Vickers - Defender - Jersey No: 33","Nile John - Midfielder - Jersey No: 28","Dane Scarlett - Forward - Jersey No: 33",],
     "Nottingham Forest": ["Matt Turner (Goalkeeper) - Jersey #1","Odysseas Vlachodimos (Goalkeeper) - Jersey #23","Murillo (Centre-Back) - Jersey #40","Nuno Tavares (Left-Back) - Jersey #3","Neco Williams (Right-Back) - Jersey #7","Ibrahim Sangaré (Defensive Midfield) - Jersey #6","Morgan Gibbs-White (Attacking Midfield) - Jersey #10","Anthony Elanga (Left Winger) - Jersey #21","Taiwo Awoniyi (Centre-Forward) - Jersey #9","Chris Wood (Centre-Forward) - Jersey #11","Matz Sels (Goalkeeper) - Jersey #26","Wayne Hennessey (Goalkeeper) - Jersey #13","Moussa Niakhaté (Centre-Back) - Jersey #19","Andrew Omobamidele (Centre-Back) - Jersey #32","Willy Boly (Centre-Back) - Jersey #30","Felipe (Centre-Back) - Jersey #18","Harry Toffolo (Left-Back) - Jersey #15","Gonzalo Montiel (Right-Back) - Jersey #29","Danilo (Central Midfield) - Jersey #28","Nicolás Domínguez (Central Midfield) - Jersey #16","Giovanni Reyna (Attacking Midfield) - Jersey #20",],
    "West Ham": ["Lukasz Fabianski (#1) - Goalkeeper (Poland)","Alphonse Areola (#23) - Goalkeeper (France)","Joseph Anang (#49) - Goalkeeper (England)","Jacob Knightbridge (#55) - Goalkeeper (England)","Ben Johnson (#2) - Defender (England)","Aaron Cresswell (#3) - Defender (England)","Kurt Zouma (#4) - Defender (France)","Vladimír Coufal (#5) - Defender (Czech Republic)","Angelo Ogbonna (#21) - Defender (Italy)","Nayef Aguerd (#27) - Defender (Morocco)","Emerson (#33) - Defender (Italy)","Levi Laing (#53) - Defender (England)","Kaelan Casey (#42) - Defender (England)","Konstantinos Mavropanos (#15) - Defender (Greece)","Lucas Paquetá (#10) - Midfielder (Brazil)","Tomás Soucek (#28) - Midfielder (Czech Republic)","Kamarai Simon-Swyer (#58) - Midfielder (England)","George Earthy (#40) - Midfielder (England)","Edson Álvarez (#19) - Midfielder (Mexico)","James Ward-Prowse (#7) - Midfielder (England)","Mohammed Kudus (#14) - Midfielder (Ghana)","Kalvin Phillips (#11) - Midfielder (England)","Michail Antonio (#9) - Forward (Jamaica)","Maxwel Cornet (#17) - Forward (Cote D’Ivoire)","Danny Ings (#18) - Forward (England)","Jarrod Bowen (#20) - Forward (England)","Divin Mubama (#45) - Forward (England)",],
  // Add more teams and players here as needed
  };

  // Display players for each team
  for (var team in players) {
    playerListSection.innerHTML += "<h2>" + team + "</h2><ul>";
    for (var i = 0; i < players[team].length; i++) {
      playerListSection.innerHTML += "<li>" + players[team][i] + "</li>";
    }
    playerListSection.innerHTML += "</ul>";
  }
}
