function togglePlayers() {
  var playerListSection = document.getElementById("player-list");
  playerListSection.innerHTML = ""; // Clear existing content

  // Define player information for each team
  var players = {
    "AC Milan": ["Mike Maignan (#16) - Goalkeeper","Marco Sportiello (#57) - Goalkeeper","Lapo Nava (#69) - Goalkeeper","Antonio Mirante (#83) - Goalkeeper","Fikayo Tomori (#23) - Centre-Back","Malick Thiaw (#28) - Centre-Back","Pierre Kalulu (#20) - Centre-Back","Matteo Gabbia (#46) - Centre-Back","Simon Kjaer (#24) - Centre-Back","Theo Hernández (#19) - Left-Back","Davide Calabria (#2) - Right-Back","Filippo Terracciano (#38) - Right-Back","Alessandro Florenzi (#42) - Right-Back","Ismaël Bennacer (#4) - Defensive Midfield","Yacine Adli (#7) - Defensive Midfield","Ruben Loftus-Cheek (#8) - Central Midfield","Tijjani Reijnders (#14) - Central Midfield","Yunus Musah (#80) - Central Midfield","Tommaso Pobega (#32) - Central Midfield","Rafael Leão (#10) - Left Winger","Christian Pulisic (#11) - Right Winger","Samuel Chukwueze (#21) - Right Winger","Noah Okafor (#17) - Centre-Forward","Luka Jović (#15) - Centre-Forward","Olivier Giroud (#9) - Centre-Forward",],
    "Inter": ["Emil Audero (#77) - Goalkeeper","Yann Sommer (#1) - Goalkeeper","Raffaele Di Gennaro (#12) - Goalkeeper","Alessandro Bastoni (#95) - Centre-Back","Benjamin Pavard (#28) - Centre-Back","Yann Bisseck (#31) - Centre-Back","Stefan de Vrij (#6) - Centre-Back","Francesco Acerbi (#15) - Centre-Back","Federico Dimarco (#32) - Left-Back","Matteo Darmian (#36) - Right-Back","Hakan Çalhanoğlu (#20) - Defensive Midfield","Kristjan Asllani (#21) - Defensive Midfield","Nicolò Barella (#23) - Central Midfield","Davide Frattesi (#16) - Central Midfield","Henrikh Mkhitaryan (#22) - Central Midfield","Davy Klaassen (#14) - Central Midfield","Stefano Sensi (#5) - Central Midfield","Denzel Dumfries (#2) - Right Midfield","Tajon Buchanan (#17) - Right Midfield","Juan Cuadrado (#7) - Right Midfield","Carlos Augusto (#30) - Left Midfield","Lautaro Martínez (#10) - Centre-Forward","Marcus Thuram (#9) - Centre-Forward","Marko Arnautovic (#8) - Centre-Forward","Alexis Sánchez (#70) - Centre-Forward",],
    "Udinese":  ["Maduka Okoye (#40) - Goalkeeper","Marco Silvestri (#1) - Goalkeeper","Daniele Padelli (#93) - Goalkeeper","Nehuén Pérez (#18) - Centre-Back","Jaka Bijol (#29) - Centre-Back","Thomas Kristensen (#31) - Centre-Back","Lautaro Giannetti (#30) - Centre-Back","Enzo Ebosse (#23) - Centre-Back","João Ferreira (#13) - Centre-Back","Christian Kabasele (#27) - Centre-Back","Antonio Tikvić (#16) - Centre-Back","James Abankwah (#14) - Centre-Back","Jordan Zemura (#33) - Left-Back","Hassane Kamara (#12) - Left-Back","Kingsley Ehizibue (#19) - Right-Back","Walace (#11) - Defensive Midfield","Lazar Samardžić (#24) - Central Midfield","Sandi Lovric (#4) - Central Midfield","Martín Payero (#32) - Central Midfield","Roberto Pereyra (#37) - Central Midfield","Oier Zarraga (#6) - Central Midfield","Festy Ebosele (#2) - Right Midfield","David Pejičić (#79) - Attacking Midfield","Florian Thauvin (#26) - Right Winger","Lorenzo Lucca (#17) - Centre-Forward","Brenner (#22) - Centre-Forward","Isaac Success (#7) - Centre-Forward","Keinan Davis (#9) - Centre-Forward","Gerard Deulofeu (#10) - Centre-Forward",],
    "Juventus":  ["Wojciech Szczęsny (#1) - Goalkeeper","Carlo Pinsoglio (#23) - Goalkeeper","Mattia Perin (#36) - Goalkeeper","Mattia De Sciglio (#2) - Right-Back","Gleison Bremer (#3) - Centre-Back","Federico Gatti (#4) - Centre-Back","Luiz da Silva Danilo (#6) - Right-Back","Alex Sandro (#12) - Left-Back","Daniele Rugani (#24) - Centre-Back","Andrea Cambiaso (#27) - Centre-Back","Tiago Djaló (#33) - Centre-Back","Manuel Locatelli (#5) - Central Midfield","Paul Pogba (#10) - Central Midfield","Filip Kostić (#11) - Left Midfield","Weston McKennie (#16) - Central Midfield","Fabio Miretti (#20) - Central Midfield","Nicoló Fagioli (#21) - Central Midfield","Timothy Weah (#22) - Right Midfield","Adrien Rabiot (#25) - Central Midfield","Carlos Alcaraz (#26) - Central Midfield","Hans Nicolussi Caviglia (#41) - Left Midfield","Federico Chiesa (#7) - Right Winger","Dušan Vlahović (#9) - Centre-Forward","Arkadiusz Milik (#14) - Centre-Forward","Kenan Yildiz (#15) - Centre-Forward","Samuel Iling-Junior (#17) - Centre-Forward","Moise Kean (#18) - Centre-Forward",],
    "Bologna":  ["Lukasz Skorupski (Jersey No. 28) - Goalkeeper, aged 32, market value: €3.50 million","Federico Ravaglia (Jersey No. 34) - Goalkeeper, aged 24, market value: €450,000","Nicola Bagnolini (Jersey No. 23) - Goalkeeper, aged 20, market value: €200,000"."Riccardo Calafiori (Jersey No. 33) - Centre-Back, aged 21, market value: €25.00 million","Sam Beukema (Jersey No. 31) - Centre-Back, aged 25, market value: €15.00 million","Jhon Lucumí (Jersey No. 26) - Centre-Back, aged 25, market value: €11.00 million","Mihajlo Ilić (Jersey No. 4) - Centre-Back, aged 20, market value: €4.00 million","Adama Soumaoro (Jersey No. 5) - Centre-Back, aged 31, market value: €3.00 million","Victor Kristiansen (Jersey No. 15) - Left-Back aged 21, market value: €15 million","Tommaso Corazza (Jersey No. 16) - Left-Back, aged 19, market value:€1million","Charalampos Lykogiannis (Jersey No. 22) - Left-Back, aged 30, market value: million","Stefan Posch (Jersey No. 3) - Right-Back, aged 26, market value: €14.00 million","Lorenzo De Silvestri (Jersey No. 29) - Right-Back, aged 35, market value: €400,000","Nikola Moro (Jersey No. 6) - Defensive Midfield, aged 26, market value: €6.50 million","Oussama El Azzouzi (Jersey No. 17) - Defensive Midfield, aged 22, market value: €2.00 million","Giovanni Fabbian (Jersey No. 80) - Central Midfield, aged 21, market value: €12.00 million","Remo Freuler (Jersey No. 8) - Central Midfield, aged 32, market value: €6.50 million","Michel Aebischer (Jersey No. 20) - Central Midfield, aged 27, market value: €6.00 million","Kacper Urbanski (Jersey No. 82) - Central Midfield, aged 19, market value: €4.00 million","Lewis Ferguson (Jersey No. 19) - Attacking Midfield, aged 24, market value: €24.00 million","Jesper Karlsson (Jersey No. 10) - Left Winger, aged 25, market value: €10.00 million","Riccardo Orsolini (Jersey No. 7) - Right Winger, aged 27, market value: €14.00 million","Dan Ndoye (Jersey No. 11) - Right Winger, aged 23, market value: €10.00 million","Alexis Saelemaekers (Jersey No. 56) - Right Winger, aged 24, market value: €10.00 million","Jens Odgaard (Jersey No. 21) - Right Winger, aged 25, market value: €4.00 million","Joshua Zirkzee (Jersey No. 9) - Centre-Forward, aged 22, market value: €40.00 million","Santiago Castro (Jersey No. 18) - Centre-Forward, aged 19, market value: €12.00 million.",],
    "Roma": ["Rui Patrício (#1) - Goalkeper, Age: 36","Mile Svilar (#99) - Goalkeeper, Age: 24","Pietro Boer (#63) - Goalkeeper, Age: 21","Evan Ndicka (#5) - Centre-Back, Age: 24","Gianluca Mancini (#23) - Centre-Back, Age: 28","Dean Huijsen (#3) - Centre-Back, Age: 19","Diego Llorente (#14) - Centre-Back, Age: 30","Chris Smalling (#6) - Centre-Back, Age: 34","Angeliño (#69) - Left-Back, Age: 27","Leonardo Spinazzola (#37) - Left-Back, Age: 31","Rasmus Kristensen (#43) - Right-Back, Age: 26","Rick Karsdorp (#2) - Right-Back, Age: 29","Zeki Çelik (#19) - Right-Back, Age: 27","Bryan Cristante (#4) - Defensive Midfield, Age: 29","Leandro Paredes (#16) - Defensive Midfield, Age: 29","Edoardo Bove (#52) - Central Midfield, Age: 21","Houssem Aouar (#22) - Central Midfield, Age: 25","Renato Sanches (#20) - Central Midfield, Age: 26","Nicola Zalewski (#59) - Left Midfield, Age: 22","Lorenzo Pellegrini (#7) - Attacking Midfield, Age: 27","Tommaso Baldanzi (#35) - Attacking Midfield, Age: 21","Stephan El Shaarawy (#92) - Left Winger, Age: 31","Paulo Dybala (#21) - Second Striker, Age: 30","Tammy Abraham (#9) - Centre-Forward, Age: 26","Romelu Lukaku (#90) - Centre-Forward, Age: 30",
"Sardar Azmoun (#17) - Centre-Forward, Age: 29",],
    "Atalanta": ["Marco Carnesecchi (Jersey No. 29) - Goalkeeper, aged 23, market value: €15.00 million","Juan Musso (Jersey No. 1) - Goalkeeper, aged 29, market value: €6.50 million","Francesco Rossi (Jersey No. 31) - Goalkeeper, aged 32, market value: €100,000","Giorgio Scalvini (Jersey No. 42) - Centre-Back, aged 20, market value: €45.00 million","Berat Djimsiti (Jersey No. 19) - Centre-Back, aged 31, market value: €10.00 million","Isak Hien (Jersey No. 4) - Centre-Back, aged 25, market value: €9.00 million","Sead Kolasinac (Jersey No. 23) - Centre-Back, aged 30, market value: €8.00 million","Rafael Tolói (Jersey No. 2) - Centre-Back, aged 33, market value: €4.00 million","José Luis Palomino (Jersey No. 6) - Centre-Back, aged 34, market value: €1.00 million","Giovanni Bonfanti (Jersey No. 43) - Centre-Back, aged 21","Marten de Roon (Jersey No. 15) - Defensive Midfield, aged 33, market value: €8.00 million","Éderson (Jersey No. 13) - Central Midfield, aged 24, market value: €30.00 million","Mario Pasalic (Jersey No. 8) - Central Midfield, aged 29, market value: €13.00 million","Michel Adopo (Jersey No. 25) - Central Midfield, aged 23, market value: €1.00 million","Emil Holm (Jersey No. 3) - Right Midfield, aged 23, market value: €12.00 million","Davide Zappacosta (Jersey No. 77) - Right Midfield, aged 31, market value: €6.00 million","Hans Hateboer (Jersey No. 33) - Right Midfield, aged 30, market value: €4.00 million","Matteo Ruggeri (Jersey No. 22) - Left Midfield, aged 21, market value: €15.00 million","Mitchel Bakker (Jersey No. 20) - Left Midfield, aged 23, market value: €7.00 million","Teun Koopmeiners (Jersey No. 7) - Attacking Midfield, aged 26, market value: €40.00 million","Charles De Ketelaere (Jersey No. 17) - Attacking Midfield, aged 23, market value: €30.00 million","Aleksey Miranchuk (Jersey No. 59) - Attacking Midfield, aged 28, market value: €9.00 million","Ademola Lookman (Jersey No. 11) - Second Striker, aged 26, market value: €30.00 million","Gianluca Scamacca (Jersey No. 90) - Centre-Forward, aged 25, market value: €25.00 million","El Bilal Touré (Jersey No. 10) - Centre-Forward, aged 22, market value: €20.00 million",],
    "Lazio": ["Ivan Provedel (Goalkeeper) - Kit Number: 94","Christos Mandas (Goalkeeper) - Kit Number: 35","Luigi Sepe (Goalkeeper) - Kit Number: 33","Alessio Romagnoli (Centre-Back) - Kit Number: 13","Nicolò Casale (Centre-Back) - Kit Number: 15","Mario Gila (Centre-Back) - Kit Number: 34","Patric (Centre-Back) - Kit Number: 4","Luca Pellegrini (Left-Back) - Kit Number: 3","Adam Marusic (Right-Back) - Kit Number: 77","Elseid Hysaj (Right-Back) - Kit Number: 23","Nicolò Rovella (Defensive Midfield) - Kit Number: 65","Danilo Cataldi (Defensive Midfield) - Kit Number: 32","Mattéo Guendouzi (Central Midfield) - Kit Number: 8","Luis Alberto (Central Midfield) - Kit Number: 10","Matías Vecino (Central Midfield) - Kit Number: 5","Manuel Lazzari (Right Midfield) - Kit Number: 29","Daichi Kamada (Attacking Midfield) - Kit Number: 6","André Anderson (Attacking Midfield) - Kit Number: 28","Mattia Zaccagni (Left Winger) - Kit Number: 20","Diego González (Left Winger) - Kit Number: 22","Saná Fernandes (Left Winger) - Kit Number: 70","Gustav Isaksen (Right Winger) - Kit Number: 18","Felipe Anderson (Right Winger) - Kit Number: 7","Pedro (Right Winger) - Kit Number: 9","Cristiano Lombardi (Right Winger) - Kit Number: 87","Taty Castellanos (Centre-Forward) - Kit Number: 19","Ciro Immobile (Centre-Forward) - Kit Number: 17,],
    "Napoli": ["Alex Meret (Goalkeeper) - Jersey #1","Pierluigi Gollini (Goalkeeper) - Jersey #95","Nikita Contini (Goalkeeper) - Jersey #14","Hubert Idasiak (Goalkeeper) - Jersey #16","Amir Rrahmani (Centre-Back) - Jersey #13","Natan (Centre-Back) - Jersey #3","Leo Østigård (Centre-Back) - Jersey #55","Juan Jesus (Centre-Back) - Jersey #5","Mathías Olivera (Left-Back) - Jersey #17","Mário Rui (Left-Back) - Jersey #6","Giovanni Di Lorenzo (Right-Back) - Jersey #22","Pasquale Mazzocchi (Right-Back) - Jersey #30","Stanislav Lobotka (Defensive Midfield) - Jersey #68","Leander Dendoncker (Defensive Midfield) - Jersey #32","Diego Demme (Defensive Midfield) - Jersey #4","Frank Anguissa (Central Midfield) - Jersey #99","Piotr Zieliński (Central Midfield) - Jersey #20","Jens Cajuste (Central Midfield) - Jersey #24
"Jesper Lindelöf (Attacking Midfield) - Jersey #29","Hamed Junior Traorè (Attacking Midfield) - Jersey #8","Khvicha Kvaratskhelia (Left Winger) - Jersey #77","Matteo Politano (Right Winger) - Jersey #21","Cyril Ngonge (Right Winger) - Jersey #26","Giacomo Raspadori (Second Striker) - Jersey #81","Victor Osimhen (Centre-Forward) - Jersey #9","Giovanni Simeone (Centre-Forward) - Jersey #18",],
    "Fiorentina": ["Oliver Christensen (No. 53) - Market value: €3.80 million","Pietro Terracciano (No. 1) - Market value: €2.50 million","Tommaso Martinelli (No. 30) - Market value: €1.00 million","Tommaso Vannucchi (No. 40) - Market value: €400,000","Nikola Milenković (No. 4) - Center-back, Market value: €16.00 million","Lucas Martínez Quarta (No. 28) - Center-back, Market value: €14.00 million","Luca Ranieri (No. 16) - Center-back, Market value: €5.00 million","Pietro Comuzzo (No. 37) - Center-back, Market value: €700,000","Fabiano Parisi (No. 65) - Left-back, Market value: €9.50 million","Cristiano Biraghi (No. 3) - Left-back, Market value: €4.00 million","Dodô (No. 2) - Right-back, Market value: €20.00 million","Michael Kayode (No. 33) - Right-back, Market value: €15.00 million","Davide Faraoni (No. 22) - Right-back, Market value: €2.00 million","Arthur Melo (No. 6) - Defensive midfielder, Market value: €15.00 million","Maxime López (No. 8) - Defensive midfielder, Market value: €9.00 million","Rolando Mandragora (No. 38) - Defensive midfielder, Market value: €8.50 million","Gaetano Castrovilli (No. 17) - Central midfielder, Market value: €8.00 million","Alfred Duncan (No. 32) - Central midfielder, Market value: €4.50 million","Giacomo Bonaventura (No. 5) - Central midfielder, Market value: €3.00 million","Gino Infantino (No. 19) - Central midfielder, Market value: €3.00 million","Antonín Barák (No. 72) - Attacking midfielder, Market value: €5.00 million","Christian Kouamé (No. 99) - Left winger, Market value: €9.00 million","Riccardo Sottil (No. 7) - Left winger, Market value: €6.50 million","Nicolás González (No. 10) - Right winger, Market value: €40.00 million","Jonathan Ikoné (No. 11) - Right winger, Market value: €13.00 million","Lucas Beltrán (No. 9) - Center-forward, Market value: €16.00 million","M’Bala Nzola (No. 18) - Center-forward, Market value: €8.00 million","Andrea Belotti (No. 20) - Center-forward, Market value: €6.00 million",],
    "Torino":[],
    "Monzo": ["Michele Di Gregorio (No. 16) - Goalkeeper, Market value: €15.00 million","Alessandro Sorrentino (No. 23) - Goalkeeper, Market value: €800,000","Stefano Gori (No. 66) - Goalkeeper, Market value: €700,000","Pablo Marí (No. 22) - Center-back, Market value: €5.00 million","Andrea Carboni (No. 44) - Center-back Market value: €4.00 million","Armando Izzo (No. 4) - Center-back, Market value: €2.50 million","Luca Caldirola (No. 5) - Center-back, Market value: €1.50 million","Davide Bettella (No. 18) - Center-back, Market value: €1.20 million","Danilo D’Ambrosio (No. 33) - Center-back, Market value: €1.00 million","Samuele Birindelli (No. 19) - Right-back, Market value: €3.50 million","Pedro Pereira (No. 13) - Right-back, Market value: €1.80 million","Giulio Donati (No. 2) - Right-back, Market value: €400,000","Matteo Pessina (No. 32) - Central midfielder, Market value: €15.00 million","Roberto Gagliardini (No. 6) - Central midfielder, Market value: €4.00 million","Warren Bondo (No. 38) - Central midfielder, Market value: €2.50 million","José Machín (No. 7) - Central midfielder, Market value: €1.40 million","Jean-Daniel Akpa Akpro (No. 8) - Central midfielder, Market value: €1.00 million","Patrick Ciurria (No. 84) - Right midfielder, Market value: €5.00 million","Georgios Kyriakopoulos (No. 77) - Left midfielder, Market value: €4.00 million","Valentín Carboni (No. 21) - Attacking midfielder, Market value: €15.00 million","Andrea Colpani (No. 28) - Attacking midfielder, Market value: €15.00 million","Samuele Vignato (No. 80) - Attacking midfielder, Market value: €4.00 million","Daniel Maldini (No. 27) - Attacking midfielder, Market value: €3.00 million","Matija Popovic (No. 79) - Attacking midfielder, Market value: €2.00 million","Alessio Zerbin (No. 20) - Left winger, Market value: €3.50 million","Papu Gómez (No. 17) - Left winger","Gianluca Caprari (No. 10) - Second striker, Market value: €5.00 million","Lorenzo Colombo (No. 9) - Center-forward, Market value: €7.00 million","Dany Mota (No. 47) - Center-forward, Market value: €5.00 million","Milan Djuric (No. 11) - Center-forward, Market value: €1.50 million",],
    "Genoa": ["Michele Di Gregorio (No. 16) - Goalkeeper, Market value: €15.00 million","Alessandro Sorrentino (No. 23) - Goalkeeper, Market value: €800,000","Stefano Gori (No. 66) - Goalkeeper, Market value: €700,000","Pablo Marí (No. 22) - Center-back, Market value: €5.00 million","Andrea Carboni (No. 44) - Center-back, Market value: €4.00 million","Armando Izzo (No. 4) - Center-back, Market value: €2.50 million","Luca Caldirola (No. 5) - Center-back, Market value: €1.50 million","Davide Bettella (No. 18) - Center-back, Market value: €1.20 million","Danilo D’Ambrosio (No. 33) - Center-back, Market value: €1.00 million","Samuele Birindelli (No. 19) - Right-back, Market value: €3.50 million","Pedro Pereira (No. 13) - Right-back, Market value: €1.80 million","Giulio Donati (No. 2) - Right-back, Market value: €400,000","Matteo Pessina (No. 32) - Central midfielder, Market value: €15.00 million","Roberto Gagliardini (No. 6) - Central midfielder, Market value: €4.00 million?","Warren Bondo (No. 38) - Central midfielder, Market value: €2.50 million","José Machín (No. 7) - Central midfielder, Market value: €1.40 million","Jean-Daniel Akpa Akpro (No. 8) - Central midfielder, Market value: €1.00 million","Patrick Ciurria (No. 84) - Right midfielder, Market value: €5.00 million","Georgios Kyriakopoulos (No. 77) - Left midfielder, Market value: €4.00 million","Valentín Carboni (No. 21) - Attacking midfielder, Market value: €15.00 million","Andrea Colpani (No. 28) - Attacking midfielder, Market value: €15.00 million","Samuele Vignato (No. 80) - Attacking midfielder, Market value: €4.00 million","Daniel Maldini (No. 27) - Attacking midfielder, Market value: €3.00 million","Matija Popovic (No. 79) - Attacking midfielder, Market value: €2.00 million","Alessio Zerbin (No. 20) - Left winger, Market value: €3.50 million","Papu Gómez (No. 17) - Left winger","Gianluca Caprari (No. 10) - Second striker, Market value: €5.00 million","Lorenzo Colombo (No. 9) - Center-forward, Market value: €7.00 million","Dany Mota (No. 47) - Center-forward, Market value: €5.00 million","Milan Djuric (No. 11) - Center-forward, Market value: €1.50 million",],
    "Lecce": ["Dorgu (No. 13) - Goalkeeper","Krstovic (No. 9) - Goalkeeper","Piccoli (No. 91) - Goalkeeper","Pablo Marí (No. 22) - Center-back","Andrea Carboni (No. 44) - Center-back","Armando Izzo (No. 4) - Center-back","Luca Caldirola (No. 5) - Center-back","Davide Bettella (No. 18) - Center-back","Danilo D’Ambrosio (No. 33) - Center-back","Samuele Birindelli (No. 19) - Right-back","Pedro Pereira (No. 13) - Right-back","Giulio Donati (No. 2) - Right-back","Matteo Pessina (No. 32) - Central midfielder","Roberto Gagliardini (No. 6) - Central midfielder","Warren Bondo (No. 38) - Central midfielder","José Machín (No. 7) - Central midfielder","Jean-Daniel Akpa Akpro (No. 8) - Central midfielder","Patrick Ciurria (No. 84) - Right midfielder","Georgios Kyriakopoulos (No. 77) - Left midfielder","Valentín Carboni (No. 21) - Attacking midfielder","Andrea Colpani (No. 28) - Attacking midfielder","Samuele Vignato (No. 80) - Attacking midfielder","Daniel Maldini (No. 27) - Attacking midfielder","Matija Popovic (No. 79) - Attacking midfielder","Alessio Zerbin (No. 20) - Left winger","Papu Gómez (No. 17) - Left winger","Gianluca Caprari (No. 10) - Second striker","Lorenzo Colombo (No. 9) - Center-forward","Dany Mota (No. 47) - Center-forward","Milan Djuric (No. 11) - Center-forward",],
    "Cagliari": [],
    "Verona": [],
    "Empoli": [],
    "Frosinone": [],
    "Sassuolo":[],
    "Salernitana":[],

    // Add more teams and players here as needed
  };

  // Display players for each team
  for (var team in players) {
    playerListSection.innerHTML += "<h2>" + team + "</h2><ul>";
    for (var i = 0; i < players[team].length; i++) {
      playerListSection.innerHTML += "<li>" + players[team][i] + "</li>";
    }
    playerListSection.innerHTML += "</ul>";
  }
}
